
spring:
  profiles:
    active: dev
---
server:
  servlet:
    context-path: /utms


spring:
  profiles: dev
  thymeleaf:
    cache: false
  messages:
    basename: i18n.login
  datasource:
    url: jdbc:mysql://localhost:3306/read_data?useUnocode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    favicon:
      enabled: false
    #静态资源文件访问位置前缀
    # 当访问static/img/image.jpg时原本的默认“/**”会去classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/下查找文件
    static-path-pattern: /static/**
   # static-locations: classpath:/static/
logging:
  level.com.ecust.utms: trace
  file: utms.log
  #logging.patter.console:  在控制台输出的日志的格式
---
spring:
  profiles: prod

